# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('parameters', models.CharField(max_length=1024)),
                ('state', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('opt', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
