# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_auto_20160922_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='pressure',
            field=models.DecimalField(decimal_places=2, default=0.9, max_digits=3),
        ),
    ]
