# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_tasklist_pressure'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='timer',
            field=models.IntegerField(default=20, max_length=10),
        ),
    ]
