# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_machinelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='state',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='timer',
            field=models.IntegerField(default=20),
        ),
    ]
