# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_auto_20160927_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='detail',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
